[project]
name = 'Blockchain-Based-Vaccine-Certificate-Verification'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.certificate-issuance]
path = 'contracts/certificate-issuance.clar'
clarity_version = 2
epoch = 2.5

[contracts.privacy-management]
path = 'contracts/privacy-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.vaccination-record]
path = 'contracts/vaccination-record.clar'
clarity_version = 2
epoch = 2.5

[contracts.verification]
path = 'contracts/verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
